### ISSUE TITLE
Missing Quality Patch Option for Magento Version 2.4.6-p4

### ISSUE THREAD

**Issue by lakshmana** [magento/quality-patches#119]
Hello, it seems that the latest quality patch does not include an option for version 2.4.6-p4. There are still numerous patches necessary for this version, such as MDVA-12304.
Could someone please take a look on this issue?
<img width="238" alt="image" src="https://github.com/magento/quality-patches/assets/3132026/62cc19d9-9d21-47ca-941a-420b2912f641">

**Comment by gbobts** [comment]
Not sure why this issue is closed, as the 2.4.7 version still doesn't appear on the page

**Comment by gbobts** [comment]
@lakshmana could you detail why you closed the issue yourself ? Thanks :)

**Comment by lakshmana** [comment]
@gbobts The issue was created for version 2.4.6-p4, and the quality patches for this version are now available. Therefore, I closed the issue, despite the fact that the patches for version 2.4.7 are not yet available, which is somewhat disappointing. I would rather open a new issue for version 2.4.7 than simply change the title of the existing one.
![image](https://github.com/magento/quality-patches/assets/3132026/650950ee-927a-4c18-807b-c5015e6078a1)

**Comment by gbobts** [comment]
Would you consider creating a pull request for a 2.4.7-compatible patch ?
