### ISSUE TITLE
Quality patches for 2.4.7

### ISSUE THREAD

**Issue by jbruni** [magento/quality-patches#122]
I don't see any patch for version 2.4.7 at https://experienceleague.adobe.com/tools/commerce-quality-patches/index.html

Version 2.4.7 is not even listed in the releases dropdown.

Does this mean that all listed patches were already integrated at version 2.4.7 ?

I am doing an upgrade from 2.4.6 to 2.4.7 and I am willing to keep only the necessary `QUALITY_PATCHES` listed at `.magento.env.yaml`

Shall I remove them all?

Thanks.

**Comment by hostep** [comment]
Version 1.1.49 got released yesterday: https://github.com/magento/quality-patches/releases

So I guess this issue can be closed?

**Comment by jbruni** [comment]
Hi @hostep - Thanks for the update!

I can see patches listed for 2.4.7 and 2.4.7-p1 now.

Yes, I agree this issue can be closed.
