### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by simonrl** [magento/quality-patches#126]
Hi,

not an issue, just a question.

No update for the latest versions, no reactions to new issues - is this repository still maintained?

We need to remove Quality Patches from upgraded stores which raises all kinds of issues.

I'd just like to know where this is going and if it will become reliable again in the future.

Thanks
Simon

**Comment by hostep** [comment]
I wondered the same and asked the question on Slack some months ago, the answer is not very clear to be honest:
![Screenshot 2024-07-26 at 13 03 25](https://github.com/user-attachments/assets/9489ff75-3eab-46a6-b0a7-c07bdca24d54)


If it helps: w've never used this quality-patches tool ourselves, but cherry-pick the patches we need (rework them if necessary) and apply them using https://github.com/vaimo/composer-patches/ or https://github.com/cweagans/composer-patches in our projects

**Comment by simonrl** [comment]
Hey, 

thanks for the reply.
The answer from Slack is clear in one thing: it's unreliable.

Guess we'll then use the tool in the same way as you suggested.

**Comment by hostep** [comment]
Looks like it's still active, a new version got released yesterday: https://github.com/magento/quality-patches/releases

**Comment by simonrl** [comment]
Closing bc a new version got released.
