### ISSUE TITLE
Patch [ACSD-62591]: Mentioned to be available for Magento 2.4.7-p2, but it is not

### ISSUE THREAD

**Issue by dandrikop** [magento/quality-patches#129]
With the issue https://github.com/magento/magento2/issues/39221, the patch ACSD-62591 was reported to fix the problem with the FPC Cache on Magento 2.4.7. However, the below link mentions that the patch ACSD-62591 fixes something else:

[https://experienceleague.adobe.com/en/docs/commerce-operations/tools/quality-patches-tool/patches-available-in-qpt/v1-1-55/overview](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexperienceleague.adobe.com%2Fen%2Fdocs%2Fcommerce-operations%2Ftools%2Fquality-patches-tool%2Fpatches-available-in-qpt%2Fv1-1-55%2Foverview&data=05%7C02%7Cglo24157%40adobe.com%7C248b6f35f34f4f8f22f908dd13eb7b9c%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C638688624317402779%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=nZWX5TwtRBmazHf2k0kl57bCNDMwj1kfAEns84FOM%2BM%3D&reserved=0)

In addition, I tried to install the patch on my test environment which is on Magento 2.4.7-p2 and it does not seem to be available for that version of Magento (see below screenshot). Please do not close issues before we confirm successful resolution.

![image](https://github.com/user-attachments/assets/bde0ecde-0932-4651-a955-eef3183d7b49)

**Comment by dandrikop** [comment]
Hello @engcom-Hotel,

Can you please check the patch ACSD-62591?

**Comment by engcom-Hotel** [comment]
Hello @dandrikop,

I can see the issue has been closed by you. Are you able to find the fix in the patch mentioned?

**Comment by dandrikop** [comment]
Hello @engcom-Hotel,

I found the reason that the patch ACSD-62591 was not shown when I executed the below command:
`php vendor/bin/magento-patches status`

I needed to do the below update first, and after that the patch was shown and successfully installed:
`composer update magento/quality-patches`

Following I tried the patch ACSD-62591 on my test environment running Magento 2.4.7-p2, and it seemed that the FPC worked for my multi-store Magento implementation. Namely, subsequent requests for the same page were served from FPC, as the value of the header "**X-magento-cache-debug**" was "HIT". Before the installation of the patch the value of that header was always "MISS".

However, comparing the behavior with older Magento versions, I noticed that on Magento 2.4.7 the cache keys were of the form "**id:98fb911a51a68278bdbad0f7f7d2c277ab22e4c8**", while for example on Magento 2.4.6, the cache keys were of the form "**MAGE_RUN_TYPE_STORE_MAGE_RUN_CODE_GREEK_DLA_7A9B03C68AFC27012A3E10C4655D6F14147799FA**"; i.e. they included the attributes MAGE_RUN_TYPE and MAGE_RUN_CODE.

The first impact that I noticed was that a 3rd party module I have for Cache Warming didn't work on Magento 2.4.7 as it worked on Magento 2.4.6. Can you please check that the described behavior on Magento 2.4.7 is the correct one?

**Comment by engcom-Hotel** [comment]
Sure I will check @dandrikop!

Meanwhile can you please post a new issue on the Magento2 repo explaining the exact issue you are facing if the cache keys exist in the form you explained in your comment?

Thanks
