### ISSUE TITLE
Windows File Lock

### ISSUE THREAD

**Issue by robertdeboer** [magento/quality-patches#46]
When installing this package via composer on Windows 10, whether by `install` or `update`, the following error is produced:

![image](https://user-images.githubusercontent.com/446001/107699294-e301e580-6c83-11eb-8f72-525cbfd2bac8.png)

* I have increased the timeout for composer
* I have ran the command in non admin and admin mode
* I have disabled Windows for Linux Subsystems
* I have disabled the Windows feature `VirtualMachinePlatform`
* I have disable Windows Defender
* I have tried different versions of Powershell - classic and 7

Windows 10 Home 20H2 19042.804
PHP 7.4.15
Composer 2.0.9

**Comment by viktym** [comment]
Hi @robertdeboer 
Looks like some environment issue
Are you able to install any other composer packages ?
Try to clean `vendor` folder and  run composer install

**Comment by robertdeboer** [comment]
Hello @viktym 

Yes, I switched to a clean directly, and installed a fresh composer package using laravel/framework (as I know it has a lot of dependencies).

After doing that, I went back to the project, removed the vendor folder, did a `composer clearcache` and re-ran `composer install` with the same result.

If it helps any, this is not a local install - this is a checkout of a commerce cloud magneto store. So a magento-cloud cli checkout and then a composer install

**Comment by viktym** [comment]
@robertdeboer Unfortunately, Magento 2 isn't compatible yet with Composer version 2. It can be the cause of the issue.
You can downgrade composer to version 1 using for example composer selfupdate --1 and then you should be able to install Magento.

You can follow magento/community-features#302 to see when Magento will become compatible with composer version 2
