### ISSUE TITLE
Unable to apply MDVA-33975 multiple times

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/quality-patches#48]
### Description

We're running installing quality patches just after the composer install or update using the scripts section in the composer.json file:
```
    "scripts": {
        "post-install-cmd": [
            "./vendor/bin/magento-patches apply ..."
        ],
        "post-update-cmd": [
            "./vendor/bin/magento-patches apply ..."
        ]
    }
```

This makes a really good experience in the local and production environment, as just after the composer update - all patches get applied and you see exactly the same code as on production.

### Pre-requsites:
1. Magento 2.3.6-p1 installed via compose
2. Installed magento/magento-cloud-patches:1.0.9
3. Installed magento/quality-patches:1.0.18

### Steps to reproduce:
1. Execute 3 times the following command:

```bash
./vendor/bin/magento-patches apply MDVA-33975
```

### Expected result:
1. On the 1st run it should say that patch was successfully applied
2. On 2nd run it should say that patch already applied
3. On 3rd run it should say that patch already applied

Example from applying different patch - MDVA-30599:
![image](https://user-images.githubusercontent.com/1873745/112801792-fc1af600-9079-11eb-9c69-468a59578e97.png)

### Actual result:
1. ✔ On the 1st run it should say that patch was successfully applied 
2. ❌ On the 2nd run it asks to revert patches MDVA-31363 and MDVA-32714, otherwise fails
3. ❌ On 3rd run it says `patch can't be applied`
![image](https://user-images.githubusercontent.com/1873745/112802660-1d301680-907b-11eb-8ef1-52bc03acd377.png)

In case if we're not accepting revert - we have failure:
![image](https://user-images.githubusercontent.com/1873745/112802916-6c764700-907b-11eb-9737-53408f3d89e9.png)

/CC @viktym @YPyltiai

**Comment by YPyltiai** [comment]
@viktym , could you please review this issue? Thanks!

**Comment by viktym** [comment]
@ihor-sviziev I'll take a look

**Comment by viktym** [comment]
The fix has been merged into develop branch

**Comment by ihor-sviziev** [comment]
Just for history, the fix is here https://github.com/magento/magento-cloud-patches/commit/f1355ef6a7d69aba962a99ae35d3767357ac642a
