### ISSUE TITLE
MDVA-33289 not available for Magento 2.4.2

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/quality-patches#50]
**Context:** https://github.com/magento/magento2/issues/32668#issuecomment-818852792 https://github.com/magento/magento2/issues/32668#issuecomment-823028942
From the docs: 
https://support.magento.com/hc/en-us/articles/360058863531-MDVA-33289-Magento-patch-Javascript-in-address-at-checkout

> Please note that the issue was scheduled to be fixed in Magento **2.4.3**.
> Magento Commerce and Commerce Cloud 2.4.0 - **2.4.2**

Right now patch is NOT available for Magento 2.4.2

**Comment by viktym** [comment]
Hi @ihor-sviziev 
The patch is compatible with 2.4.2, so we will include 2.4.2 in the version constraint 
Thanks for reporting

**Comment by viktym** [comment]
@ihor-sviziev the fix merged into the master, target release 1.0.21

**Comment by ihor-sviziev** [comment]
Just for history - the fix is there https://github.com/magento/quality-patches/commit/e2469aee0ce8e8ebe8708141f05c894c7871a208
