### ISSUE TITLE
MDVA-38608 is always considered as not applied, even if it is

### ISSUE THREAD

**Issue by kanevbg** [magento/quality-patches#63]
This result in that the `public function __destruct` method is added on each patch apply because it thinks the patch is not applied.

the exact file is patches/os/MDVA-38608_2.3.2-p2

**Comment by agorbivskyi** [comment]
@kanevbg thanks for report, we will try to fix it in the next releases

**Comment by viktym** [comment]
Fixed in MDVA-38608_2.3.2-p2_v2.patch
