### ISSUE TITLE
MDVA-41061 compatibility version need update

### ISSUE THREAD

**Issue by aelmizeb** [magento/quality-patches#67]
In the documentation it mentioned for the **MDVA-41061** patch : https://support.magento.com/hc/en-us/articles/4413139771149-MDVA-41061-Stock-status-resets-to-saleable-when-product-saved-from-Admin
` ... Please note that the issue is scheduled to be fixed in Adobe Commerce 2.4.4.`
And : 
`Compatible with Adobe Commerce versions:
Adobe Commerce (all deployment methods) 2.3.5 - 2.4.3-p1`

But in **support-patches.json** there is a limitation on the version : ">=2.4.2 <2.4.3"

`
"MDVA-41061": {
        "categories": [
            "Inventory"
        ],
        "title": "Fixes the issue where stock status resets to salable when a product is saved from Admin.",
        "packages": {
            "magento/magento2-base": {
                ">=2.4.2 <2.4.3": {
                    "file": "os/MDVA-41061_2.4.2-p1_v2.patch"
                }
            },
            "magento/inventory-metapackage": {
                "1.2.2": {
                    "file": "os/MDVA-41061_1.2.2_v2.patch"
                }
            }
        }
    },
`

Can you please update the file with the correct version ?

**Comment by agorbivskyi** [comment]
MDVA-41015  patch has been added in 1.1.8 release to cover missed version. Thanks for reporting this
```
    "MDVA-41061": {
        "categories": [
            "Inventory"
        ],
        "title": "Fixes the issue where stock status resets to salable when a product is saved from Admin.",
        "packages": {
            "magento/magento2-base": {
                ">=2.4.2 <2.4.3": {
                    "file": "os/MDVA-41061_2.4.2-p1_v2.patch"
                },
                ">=2.4.3 <2.4.4": {
                    "file": "os/MDVA-41015_2.4.3.patch"
                }
            },
            "magento/inventory-metapackage": {
                "1.2.2": {
                    "file": "os/MDVA-41061_1.2.2_v2.patch"
                },
                ">=1.2.3 <1.2.4": {
                    "file": "os/MDVA-41015_1.2.3.patch"
                }
            }
        }
    },
```
