### ISSUE TITLE
Patch MDVA-42689 and Magento 2.4.4

### ISSUE THREAD

**Issue by nuzil** [magento/quality-patches#77]
This patch:

https://support.magento.com/hc/en-us/articles/5636430130445

Is officially comaprtible only on
**Adobe Commerce (all deployment methods) 2.3.0 - 2.4.3-p1** 

And at the same time: **Please note that the issue is scheduled to be fixed in Adobe Commerce 2.4.5.**

Which lead to situation that it cannot be installed on 2.4.4

Can you please align this? I can confirm it works on 2.4.4

**Comment by agorbivskyi** [comment]
@nuzil thanks for reporting. 
It has been already fixed in 1.1.17 release.
