### ISSUE TITLE
We can not install it on 2.4.4 with php 8.1

### ISSUE THREAD

**Issue by spyrmp** [magento/quality-patches#79]
Hello i am trying to install it via composer but i am getting the following error

![image](https://user-images.githubusercontent.com/4165165/179260574-890a4367-552c-4fe0-a9da-4a46c2ab6d8a.png)

**Comment by hostep** [comment]
Hey, try this workaround: https://github.com/magento/quality-patches/issues/71#issuecomment-1116194218

@viktym, I still believe it would be benificial if this gets executed, like mentioned in the previous ticket:
> But one of the solutions would be that the version constraint in the [composer.json file](https://github.com/magento/magento-cloud-patches/blob/03424d3196ffc344b7cb4781ae210abc29fbc32a/composer.json#L23) of the magento/magento-cloud-patches package gets changed from ^5.1 to ^5.0

**Comment by viktym** [comment]
@hostep  thanks for the advice. We are working on this.

**Comment by fredden** [comment]
@viktym please see https://github.com/magento/magento-cloud-patches/pull/87

**Comment by BaDos** [comment]
Merged changes from @viktym https://github.com/magento/magento-cloud-patches/commit/a383f43bde194bfaf15436ecedb8c3916728aaac
It will be released in MCP 1.0.19
