### ISSUE TITLE
Patch [MDVA-21095]: Not available on Magento 2 Community Edition, version 2.3.7-p3

### ISSUE THREAD

**Issue by spongejon** [magento/quality-patches#80]
I would love to be able to apply this patch to Magento 2 Community Edition, version 2.3.7-p3, but it is not available past 2.3.7-p2

**Comment by agorbivskyi** [comment]
Hello @spongejon
Unfortunately we don't have this patch for 2.3.7-p3 version, and due to the limited resources we can add only that patches which we already have.
