### ISSUE TITLE
Patch [MDVA-42768]: cannot be applied to Magento 2.4.4

### ISSUE THREAD

**Issue by pixel-paul** [magento/quality-patches#81]
It looks like the issue that this patch addresses is present in Magento 2.4.4 - can this be enabled for Magento 2.4.4?

Ref: https://github.com/magento/inventory/issues/3358

**Comment by agorbivskyi** [comment]
Hi @pixel-paul,
thanks for letting us know, I've added this to our backlog, we will update this patch in the next releases.

**Comment by agorbivskyi** [comment]
MDVA-42768 has been replaced with MDVA-42768-V2 which is not applicable to 2.4.4. We are using existing patches for QPT and we do not have this patch for 2.4.4 version at the moment.
