### ISSUE TITLE
Patch [MDVA-29400]: is not available for Magento 2.3.7-p2

### ISSUE THREAD

**Issue by vpodorozh** [magento/quality-patches#82]
### Pre req
* Magento version 2.3.7-p2  
* quality patch tools is installed and up to date (versions from 1.1.4 to 1.1.7)

### Steps to reproduce
run this command:  
```bash
./vendor/bin/magento-patches apply MDVA-29400
```

### Expected result
The patch is applied.

### Actual result
Error - patch not found
```
Magento 2 Enterprise Edition, version 2.3.7.0-patch2
Next patches weren't found: MDVA-29400. Please, check with "status" command availability of these patches for the current Magento version.
```

I see that version of this patch is available only for 2.3.4 - but not other Magento versions. However, the article says different: https://support.magento.com/hc/en-us/articles/4412546433549  
Make a note, bug that is fixed by this patch is still available on other Magento versions, including 2.3.7.-p2.

**Comment by agorbivskyi** [comment]
Hi @vpodorozh 
Unfortunately we do not have this patch for 2.3.7-p2 version and currently we do not have capacity to create a new patches for community requests.
Existing patch is applicable to the following versions -` ">=2.3.0 <=2.3.7-p1 || >=2.4.0 <=2.4.0-p1"` , you can check it here: 
https://github.com/magento/quality-patches/blob/2d29ccc4a975c3ea84149e494329e719c26a586c/support-patches.json#L4028
Information in the article is correct.
