### ISSUE TITLE
Patch [MDVA-40550]: Still happening - Could not acquire lock for index: catalog_category_product

### ISSUE THREAD

**Issue by pmonosolo** [magento/quality-patches#83]
This issue happens even after the patch has been applied.

![image](https://user-images.githubusercontent.com/66754347/183988238-c675751e-e151-45f9-9087-82973b13dc99.png)

The site was running fine for a while, but last two days issues started to happen again.

```
Category Products index process error during indexation process:
Could not acquire lock for index: catalog_category_product

```

Manual reset and reindex did not work.

Any ideas what to do?

**Comment by pmonosolo** [comment]
I unclogged it after killing a stalled indexer process. Then reran reset and reindex commands:

![image](https://user-images.githubusercontent.com/66754347/183996733-8b428534-f070-46fa-971a-d0aea354a90e.png)

I will see if this repeats again tomorrow.

**Comment by agorbivskyi** [comment]
Hi @pmonosolo 
Unfortunately we do not have capacity to troubleshoot/investigate the patches itself. All patches which were added to QPT tool have been previously checked by our team and it was confirmed they fix specific issues.
This repository intended for the QPT tool itself and for reporting issues with the tool.
