### ISSUE TITLE
MDVA-43718 not available in quality patches

### ISSUE THREAD

**Issue by OvalMedia** [magento/quality-patches#85]
Magento 2.4.4
Quality Patches 1.1.19

I am trying to install MDVA-43718 (https://support.magento.com/hc/en-us/articles/7083227422605-MDVA-43718-consumer-isn-t-authorized-to-access-resources-error-appears-when-accessing-shared-catalog) but it is not available.

```
patches apply MDVA-43718
Magento 2 Community Edition, version 2.4.4.0
Next patches weren't found: MDVA-43718. Please, check with "status" command availability of these patches for the current Magento version.
```

**Comment by ssstankiewicz** [comment]
I have the same problem in Quality Patches 1.1.24. Any news?

**Comment by agorbivskyi** [comment]
@OvalMedia this patch makes changes in B2B modules only which are not available in Community Edition
