### ISSUE TITLE
Configurable product stock is not updated from out of stock to in stock (Still out of stock) 

### ISSUE THREAD

**Issue by hhonetree** [magento/quality-patches#86]
I have Magento 2.4.4 installed in the cloud and the problem is when you change configurable product stock in this order:
1. In Stock
2. Out of stock
3. In Stock

The product detail admin shows "In Stock", but it still doesn't show up in catalog/search or GraphQl search.

**Comment by agorbivskyi** [comment]
@hhonetree this repository intended for the QPT tool itself and for reporting issues related to the tool or existing patches.
