### ISSUE TITLE
Patch [MDVA-41061-V4]:

### ISSUE THREAD

**Issue by rselvakumarnits** [magento/quality-patches#87]
This patch is solved only for Admin Product creation. If we import products using CSV same issue exists.

After product import, if we update the each product through admin then it start working properly

**Comment by agorbivskyi** [comment]
@rselvakumarnits All patches which were added to QPT tool have been previously checked by our team and it was confirmed they fix specific issues. This repository intended for the QPT tool itself and for reporting issues with the tool.
