### ISSUE TITLE
Patch [ACSD-46988]:

### ISSUE THREAD

**Issue by manish85sixty** [magento/quality-patches#89]
After applying this patch to Magento v2.4.5, It throws following error in admin CATALOG -> Product AND catalog -> Categories

Class "Symfony\Component\Intl\Currencies" not found

**Comment by atishgoswami** [comment]
Had the same issue had to resolve it by using
```bash
composer require symfony/intl -vvv
```
Seems to work after that

**Comment by manish85sixty** [comment]
Thankyou, @atishgoswami.

**Comment by peterjaap** [comment]
Wow, introducing a use statement without the dependency being present is... strange? To say the least.

**Comment by novykov** [comment]
https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/acsd-46988-graphql-currency-api-request-returns-null-values.html?lang=en
