### ISSUE TITLE
MDVA-34850 implemented but not working in 2.4.5

### ISSUE THREAD

**Issue by cptX** [magento/quality-patches#90]
Hi I checked the code in my Magento 2 Community Edition 2.4.5 and the MDVA-34850 is implemented already in the code, but still the out-of-stock options of the configurable product are not displayed as strike-through! They are displayed as if they are in-stock and they are selectable! 
I consider this very important! Without this the customers see a product as if it was in stock and they can add it to the cart. But when they they do so, they see an error message. It would be much better to see a strike-through line on the option swatch so they will no there is this option but it's out of stock currently

**Comment by agorbivskyi** [comment]
@cptX this repository intended for the QPT tool itself and for reporting issues related to the tool.
