### ISSUE TITLE
Patch [ACSD-47920]: Problem making the request

### ISSUE THREAD

**Issue by WesleyBedeschi** [magento/quality-patches#99]
I'm in version 2.4.5p1, but when I try to make a request without being logged in as a customer, I get the response below

![image](https://user-images.githubusercontent.com/61388895/223515391-d3c2565f-4cef-4bcc-8650-a4f3ab236fa6.png)

**Comment by agorbivskyi** [comment]
@WesleyBedeschi all patches which were added to QPT tool have been previously checked by our team and it was confirmed they fix specific issues. Unfortunately we do not have capacity to troubleshoot/investigate functional/application issues.
